### ISSUE TITLE
FTDI connection does not charge the Device

### ISSUE THREAD

**Issue by mnive93** [felHR85/UsbSerial#106]
The USB transfer happens between the phone and the FTDI chip. I want the phone to get charged simultaneously when it's transferring data.

FTDI chips provides 5V to the phone and the phone gets charged when it's not transferring data. 
Is there any mode I should switch on for it to power the USB bus and also allow data transfer.

**Comment by mlibre** [comment]
same. did u find any solution @mnive93 ?

**Comment by felHR85** [comment]
@mnive93 Did you finally get around this?
