### ISSUE TITLE
Permission is not granted

### ISSUE THREAD

**Issue by jonathanEp1** [felHR85/UsbSerial#114]
Hi, I am a new Android developer. 
I am trying to connect my samsung device to a PC and get a single command from a terminal software. 
However, when I open the app it immediately goes to : USB Ready-> USB disconnected ->open dialog box for allowing the application to access the device -> USB permission not granted. 

Ill be happy if you can explain to me what the issue is & how to solve it

**Comment by JugeHuge** [comment]
It's Android security feature. You need to give permission for host device to use USB connection.
It can not be bypassed by default. Only when you have custom rom with sources available then you could hack it.
https://developer.android.com/guide/topics/connectivity/usb/host.html
