### ISSUE TITLE
FTDI

### ISSUE THREAD

**Issue by z0rbal** [felHR85/UsbSerial#116]
Hi, I've been using two FT232s thru android OTG (with hub) with your code to connect to some dedicated  hardware (NMEA on port1 and my own hardware on port2)  - it's working great. However I want to use the dual FT2232H device (so there's no hub) - it reports as having two interfaces - but I guess your lib doesn't handle it - any idea how to do it? Also is there a callback for writebuffer remaining or a count of characters sent or even just string sent complete?
Thanks.

**Comment by bill-chadwick** [comment]
You just need to enumerate the interfaces on the usb device and pass the interface index into the specialised createUsbSerialDevicefunction that accepts an extra parameter - UsbSerialDevice.createUsbSerialDevice(device, connection, usbInterface);

**Comment by z0rbal** [comment]
Thanks Bill - I knew I was missing something - I'll give it a go!
