### ISSUE TITLE
Cp2102SerialDevice

### ISSUE THREAD

**Issue by RicoLewis** [felHR85/UsbSerial#130]
Hello, first :  thank for this library, it is very helpfull for my personnal project.
But I think you got a mistake in the Cp2102 Driver : parameters are added one by one but the device need one byte code for DataBits, Parity, and StopBit.
Example : I want 7 bits, parity Even with your library my code is :

serial.setDataBits(UsbSerialInterface.DATA_BITS_7);
serial.setStopBits(UsbSerialInterface.STOP_BITS_1);
serialPort.setParity(UsbSerialInterface.PARITY_EVEN);

the device receive "0x41 0x0700" and "0x41 0x????" and "0x41 0x0020" or something like that.
7 for data bits, 2 for parity_even. But when he receive the 0x41 code again, it will reset the previous command with the 0 valeur, so the 7 databits back at 8 databits.

The correct formul may be : "0x41 0x0720" in one time.

I tryed and that work perfectly.
I hope can help you with your library like this help me with.

Sorry I'm french, if you don't understand : I can try again ;)

RicoLewis.

**Comment by n3v3rf411** [comment]
Seems to be fixed in other forks:
https://github.com/mj380/UsbSerial/commit/0c30fae2710cd2e7a5f15c203b5e560f08590f44
https://github.com/RDamman/UsbSerial/commit/be1f476d1e06a21f5c94c72caafd6819d142f692
