### ISSUE TITLE
Could not receive signal.

### ISSUE THREAD

**Issue by williamtran1988** [felHR85/UsbSerial#144]
Hi All,

I am using this lib to read data transferred via USB on android. It is working well, but sometimes i could not receive signal, i have to unplug and plug usb again to make new connection then it works normal.
Is it possible we have problem with:
1. Connections timeout?
2. Thread read data is destroyed if we don't use in long time?

Can you tell me how can trigger an unexpected disconnection in this case, which help me to make sure that device is always stable state? or at least inform we know that we have a connection problem?

Thank you very much!

**Comment by Eng-O** [comment]
check for the permission maybe your device close the permission in timeout :)
