### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by geoffc2** [felHR85/UsbSerial#157]
Hello,

I've been using this library successfully (thank you!) but I have a client with some code that seems to be hitting a memory leak in the library.  His code opens and closes a UsbSerialDevice repeatedly.  The memory usage of the app gradually increases until it hits an OOM, and then I get a phone call...

I realise that this is probably not the intended use model, but it would be preferable if there was no leak to save me having to ask my client to change his code.  He is doing a close(), so I think his code is legitimate and ought to work.

Here is some test code that exhibits the problem:

```
public class MemoryLeakTest extends AndroidTestCase {

	private static final String TAG = "Memory Leak Test";

	/**
	 * Attempt 1000 connection openings/closings.
	 */
	public void testMemoryLeak() {
		LoggerI logger = new LoggerJustLog();
		for (int i = 0; i < 1000; i++) {
			doIteration();
			logger.info(TAG, "Finished iteration " + i + " with memory at " + MemoryU
					.getRamConsumedForAppMb() + " MB");
		}
	}

	/**
	 * Open a device, get permission to use it, create a connection, then close the connection.
	 */
	private void doIteration() {
		final LoggerI logger = new LoggerJustLog();
		int vendorId = 0x1B4F;
		int productId = 0x9204;
		final UsbDevice device = UsbU.getDeviceMatching(getContext(), vendorId, productId);
		if (device == null) {
			fail("No matching USB serial device found");
		} else {

		}
		final BoolHolderThreadSafe finished = new BoolHolderThreadSafe(false);

		// Define what happens when permission is granted.
		ActionI successAction = new ActionI() {
			@Override
			public void doAction() {
				// Try to connect.
				logger.info(TAG, "Starting success action");
				int baudRate = 9600;
				int stopBits = 1;
				int dataBits = 8;
				int parity = 0;

				UsbManager manager = (UsbManager) getContext().getSystemService(Context.USB_SERVICE);
				UsbDeviceConnection devCon = manager.openDevice(device);
				UsbSerialDevice serialDevice = UsbSerialDevice.createUsbSerialDevice(device, devCon);

				serialDevice.setBaudRate(baudRate);
				serialDevice.setDataBits(dataBits);
				serialDevice.setStopBits(stopBits);
				serialDevice.setParity(parity);
				serialDevice.setFlowControl(UsbSerialInterface.FLOW_CONTROL_OFF);

				serialDevice.open();

				serialDevice.close();
				finished.setValue(true);
			}
		};

		// Ask for permission and (assuming permission is granted) wait for the iteration to finish.
		UsbU.requestPermissionFor(mContext, logger, device, successAction);
		while (!finished.getValue()) {
			ThreadU.sleep(10);
		}
	}
```

There are a couple of dependencies I've not included there (e.g. UsbU, LoggerI, ActionI), but I'm hopeful it will be obvious what those parts are doing.

I've tried to debug it and the problem seems to be that the WriteThread in UsbSerialDevice doesn't finish (despite close() flagging that it ought to), and this hangs on to various objects, causing the leak.  It seems to be stuck in getWriteBuffer(), which ends up in SynchronizedBuffer.get() which does a wait().

Have I done something daft with the API or is this a genuine memory leak?

Thanks,

Geoff.

**Comment by felHR85** [comment]
@geoffc2  Could you use CanaryLeak library for finding memory leaks? I will happily solve them.

**Comment by geoffc2** [comment]
Hi Felipe,

Thanks for your response.  Unfortunately, we're not actively
working on this at the moment.

I'll let you know if I get further with it.

Regards,

Geoff.
