### ISSUE TITLE
Add example sample

### ISSUE THREAD

**Issue by StephaneBg** [felHR85/UsbSerial#16]
Please add a module with an example sample. It is simpler to look at code sometimes.

**Comment by BenLeggieroNCR** [comment]
Do you mean this? https://github.com/felHR85/SerialPortExample

**Comment by StephaneBg** [comment]
Yes, I meant that! Thank you!
Usually, example is provided in the same repository. My mistake.

**Comment by BenLeggieroNCR** [comment]
@StephaneBg  no prob!

**Comment by felHR85** [comment]
Hi @StephaneBg 
Now that UsbSerial has been ported to Android Studio maybe it would be better to add a SerialPortExample module here. What do you think?

**Comment by StephaneBg** [comment]
I'm working to port the example on gradle build system. Once this will be
made, it will be possible to merge it as a module in this repository.

Le mar. 5 janv. 2016 à 16:49, Felipe Herranz <notifications@github.com> a
écrit :

**Comment by felHR85** [comment]
Thank you! @StephaneBg

**Comment by BenLeggieroNCR** [comment]
@felHR85 I disagree; I prefer to keep libraries and their example apps separate, so those who just want to fork your repo don't have to download and manage/remove excess code they may never use.

**Comment by felHR85** [comment]
@BenLeggieroNCR It is a valid point. SerialPortExample are just two java files wouldnt be a great overhead in this particular scenario. Let's keep them separate then

**Comment by BenLeggieroNCR** [comment]
@felHR85 2 manually-written Java files, 3 generated ones, and 112 other files, totaling 19.4 MB. IMO a considerable overhead if the developer in question doesn't need an example.

**Comment by felHR85** [comment]
Other files are generated because Eclipse's fault (and mine too because there is no .gitignore added to avoid bin and other folders).

**Comment by StephaneBg** [comment]
As this library is njot published on Maven, example should be in the same
project than the library for gradle integration such as:

dependencies {

compile project(':lib')

}


Le mar. 5 janv. 2016 à 17:24, Felipe Herranz <notifications@github.com> a
écrit :

**Comment by felHR85** [comment]
Gradle integration would be great. Important reason to add it as a module

**Comment by BenLeggieroNCR** [comment]
To ignore files generated by Eclipse, use [a .gitignore specialized for Eclipse](https://github.com/github/gitignore/blob/b6f1c2f2a0daa14953ec1ed665a7063e4322837d/Global/Eclipse.gitignore)
