### ISSUE TITLE
Usb and car radio

### ISSUE THREAD

**Issue by jefferson** [felHR85/UsbSerial#160]
Is possible to connect android on car for playing music through UsbSerial?

**Comment by felHR85** [comment]
Hi @jefferson 
If that radio has a Serial interface or a CDC Usb interface it should be possible

**Comment by jefferson** [comment]
Hi @felHR85 
Thanks for your answer.

My car has a Usb Interface but I don't know if is "CDC Usb".
I tried something for get wich protocol my car use but dont's works to.

Is it possible to test to see what protocol my car uses?

**Comment by felHR85** [comment]
Steps I would follow:
- Check information about that particular radio to know more info.
- Connect the radio to your PC and using PuTTY monitor what is happening.
Maybe it uses the CAN protocol (used a lot in automotive industry) but it's hard to say

**Comment by jefferson** [comment]
Thank, I'll test the steps. 
I think the car should use [Mass Storage class (MSC device) ](http://www.kenwood.com/jp/usb/english.html) to fetch the files and play.
