### ISSUE TITLE
USB type C support

### ISSUE THREAD

**Issue by rsm123** [felHR85/UsbSerial#162]
Is USB type C  supported ?  Is there a way to make it work with FT232 chip & USB-C port?

**Comment by btelman96** [comment]
I have tested this library with one of the PL2303TA adapters and my phone (Moto Z) with a USB C port using a USB C to A adapter. That combination works fine for me. I did have to test to make sure the serial adapter worked in a PC first, since a couple of mine were faulty.

**Comment by felHR85** [comment]
As far as I know It should work for USB type C OTG.
