### ISSUE TITLE
Transfer limitation to 16kb

### ISSUE THREAD

**Issue by sewphr** [felHR85/UsbSerial#172]
Hello! i'm trying to transfer a base64 string into a serial device but the string size is much more than the 16kb default length. how can i fix this?
 
![image](https://user-images.githubusercontent.com/40405831/47951088-0dc34680-df71-11e8-8162-280c7b51cc10.png)

**Comment by felHR85** [comment]
@sewphr Did you try it? Technically it should work so give it a try. Also I am planning to add a way to change the buffer size so it is not working please reach me out

**Comment by felHR85** [comment]
@sewphr If buffer size limitation is hampering your communication you could use the synchronous api or the I/O api (InputStream OutputStream)
