### ISSUE TITLE
why not support USB human interface device class

### ISSUE THREAD

**Issue by CorrM** [felHR85/UsbSerial#175]
how to make connection to [USB human interface device class](https://en.wikipedia.org/wiki/USB_human_interface_device_class)

**Comment by felHR85** [comment]
@CorrM  what kind of device do you want to use?

**Comment by eyedol** [comment]
Also if you're using with recent versions Android, USB HID should be plug and play. You get the input from `Activity#dispatchKeyEvent` `Activity#onKeyUp` `Activity#onKeyDown`, etc Sharing more info on what you want to achieve plus the device will help
