### ISSUE TITLE
Baud rate above 115200

### ISSUE THREAD

**Issue by Vlvic** [felHR85/UsbSerial#180]
I use your library in my application that works with ELM327. The problem is that you can not get it to work at a speed of more than 115200. On Windows, this device works fine when setting a speed of 500,000. I tried elm327 with FTDI, PL2303, CP210С. Is it possible to adjust for high speed?

**Comment by felHR85** [comment]
@Vlvic 500000 is not a standard baud rate. Right now only standard baud rates are supported

**Comment by Vlvic** [comment]
Thanks for the answer!
And what is the maximum speed you can achieve using your library?

**Comment by felHR85** [comment]
@Vlvic Try this 921600

**Comment by Vlvic** [comment]
Thank you for your job!! It's works!
