### ISSUE TITLE
USB serial read buffer

### ISSUE THREAD

**Issue by mohammadVatandoost** [felHR85/UsbSerial#186]
when I receive a large file(2MB) from UsbSerial, most of data lost.
I think  read buffer is too low.

(private static final int BAUD_RATE = 921600.  )

I try with serialInputStream and UsbSerialInterface .

**Comment by felHR85** [comment]
@mohammadVatandoost 
Baud rate is not the culprit here. Current buffer size in async mode is 16kb. Use SerialnputStream to use a custom buffer size
