### ISSUE TITLE
Error: Invoke-customs are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by kjitender469** [felHR85/UsbSerial#207]

**Comment by felHR85** [comment]
```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by ElPercha** [comment]
Thank you Felipe!
I was about to make the same question and the response was already here.
It solved the issue, thank you again.
I'm a complete newbie trying to play with Android and Arduino and this library is gold

**Comment by felHR85** [comment]
@ElPercha Glad you liked it! 😀
