### ISSUE TITLE
Not receiving full json string properly

### ISSUE THREAD

**Issue by kjitender469** [felHR85/UsbSerial#209]
I have send a json string from esp32 to its Serial and reading that json string from my app via usb cable. When I parse this json string it throws exception.

**Comment by felHR85** [comment]
@kjitender469 What exception?

**Comment by kjitender469** [comment]
@felHR85 Thank you for your concern. The issue is resolved now. Actually, some garbage characters appear with JSON string when I parse the JSON. So first I have removed those garbage character and then parse the JSON string. So now it works fine.
