### ISSUE TITLE
App crashes when I return to main screen

### ISSUE THREAD

**Issue by augustopeterle** [felHR85/UsbSerial#230]
Hi, I'm using a Android 5.0 and FTDI chip.

The example asynchronous now works fine, but when I go back in App and return to main screen of my Tablet the app Crashes.

I can't debug because my USB is connected to FTDI device. I think this may be the onResume or onStop methods. 
Do you have any suggestion ?

Regards.

**Comment by felHR85** [comment]
@augustopeterle I would need mor information.
[**For debugging over Wifi you could try this**](https://github.com/felHR85/Air-Adb)
