### ISSUE TITLE
How I can get ch340 virtual com port interface?

### ISSUE THREAD

**Issue by WangLiang85** [felHR85/UsbSerial#234]
I am debuggin ch340 driver in android (https://github.com/felHR85/UsbSerial). 
I need ch340 spec such as this document https://www.silabs.com/documents/public/application-notes/AN571.pdf 
But AN571.pdf is for cp2102.

How I can get this document for ch340?

**Comment by felHR85** [comment]
@WangLiang85  As  far as I know there is no such a public document for the Ch340.

**Comment by eclectice** [comment]
Check this one https://cdn.sparkfun.com/datasheets/Dev/Arduino/Other/CH340DS1.PDF

**Comment by felHR85** [comment]
@eclectice That's more of a datasheet about pinouts and schematics. AN571 defines all usb requests available for driver developers.
