### ISSUE TITLE
FTDI device syncRead not return data

### ISSUE THREAD

**Issue by t2t-sonbui** [felHR85/UsbSerial#241]
I run _examplesync_ with FT232RL chip, but can not get anything received.  syncRead(byte[] buffer, int timeout) with _timeout_ value is 0 will make the _ReadThread_ unable to stop.

**Comment by arabine** [comment]
Same here. Must have a problem in the current implementation...

**Comment by atholbro** [comment]
It's working with Release 6.0.3, anything newer and syncRead returns 0. This is with a 1000ms timeout.

**Comment by felHR85** [comment]
@t2t-sonbui @arabine @atholbro 
You are totally right. It is confirmed that a bug was introduced. This bug only affects FTDI devices using synchronous api or Streams.
I will release a new version this weekend. In the meantime I recommend using the asynchronous api.
Sorry guys for the inconvenience.

**Comment by atholbro** [comment]
I'm just using 6.03 for now.

I'm also having an issue with larger reads failing. It seems to read about 230 bytes then cuts off. Still looking into it as it might be something on my end.

**Comment by felHR85** [comment]
@t2t-sonbui @arabine @atholbro 
Hey guys. Could you give this branch **ftdi_sync_fix** a try?
Thank you very much

**Comment by felHR85** [comment]
> I'm just using 6.03 for now.
> 
> I'm also having an issue with larger reads failing. It seems to read about 230 bytes then cuts off. Still looking into it as it might be something on my end.
Maybe you could increment the buffer?

**Comment by arabine** [comment]
Ok I will try it.

**Comment by felHR85** [comment]
Solved in 6.1.0 release
