### ISSUE TITLE
Just curious as to why you don't do release notes?

### ISSUE THREAD

**Issue by Knoxie** [felHR85/UsbSerial#244]
Lots of ways to automate it, Makes people more likely to update knowing what changed, and lets people know if breaking changes may happen for them.

**Comment by felHR85** [comment]
Since 6.0.1 I added a CHANGELOG. But further ideas of improving releases are welcomed.

**Comment by Knoxie** [comment]
![image](https://user-images.githubusercontent.com/1057404/57037480-4e9ccf00-6c25-11e9-87ad-12d7efc9a14f.png)

Just putting the change log stuff in there would be nice, instead of having to go into the changelog, but changelog is nice.  A list of all the closed 'issues' in the list would be nice.

Features:
issue 10: blah blah blah
issue 12: blah blah blah
issue 14: blah blah blah

Bug Fixes:
issue 13: blah blah
issue 15: blah blah

Just an idea, appreciate all the work you do on this!

**Comment by Knoxie** [comment]
![image](https://user-images.githubusercontent.com/1057404/57037677-d71b6f80-6c25-11e9-924f-b2865565cb8f.png)


I'm just basing this idea off other repos: https://github.com/home-assistant/home-assistant/releases

**Comment by felHR85** [comment]
Those are great ideas. I will keep them in mind for the next release.
