### ISSUE TITLE
Problem with Multiple Serial ports and FT2232D

### ISSUE THREAD

**Issue by W1il** [felHR85/UsbSerial#247]
Hi, I have been testing the example of Multiple Serial ports using a double USB-RS232 converter which internally has two [FT232R](https://www.ftdichip.com/Products/ICs/FT232R.htm) and works OK, but this manufacturer also has another model of controller, the[ FT2232D](https://www.ftdichip.com/Products/ICs/FT2232D.html), this is a double USB-RS232 converter all in a single circuit integrated, and it would be the ideal match for your app, but when I test with this controller it only lists a USB-RS232 port and does not double as it should be

With the double converter FT232R I have the following:
UsbPort:/dev/bus/usb/001/004
DeviceId:1004
ProductId:24577
VendorID:1027

UsbPort:/dev/bus/usb/001/003
DeviceId:1003
ProductId:24577
VendorID:1027

But with the FT2232D converter I have the following:
UsbPort:/dev/bus/usb/001/002
DeviceId:1002
ProductId:24592
VendorID:1027

The Android only recognizes a single USB-RS232 port and does not double as it should be

But when I use the converter with the FT2232D in my PC it works OK

Someone have any suggestions on how to correct this?

**Comment by felHR85** [comment]
@W1il 
Both should be work but I couldn't test it with any sample of a multiple serial port inside the same chipset.
Could you send me more information about the USB device [it can be done with a tool like this](https://www.thesycon.de/eng/usb_descriptordumper.shtml)

**Comment by W1il** [comment]
@felHR85,

Here is the damp file.

[DescriptorDump_Debuger-2UART.txt](https://github.com/felHR85/UsbSerial/files/3164425/DescriptorDump_Debuger-2UART.txt)

**Comment by felHR85** [comment]
Hi @W1il 
[Probably still not fixed but please try to use the multiple port example of this branch with both devices](https://github.com/felHR85/UsbSerial/tree/ftdi_multiple_interfaces)

**Comment by felHR85** [comment]
@W1il Could you test it with 6.1.0 release?

**Comment by W1il** [comment]
@felHR85, 
I just did the test with 6.1.0 release, just detect only a single port and not double as it should be the FT2232
