### ISSUE TITLE
Can I flash(update) the device using this lib?

### ISSUE THREAD

**Issue by v2kb2l** [felHR85/UsbSerial#251]
Hi,
I am want update the device with new firmware. Is this library able to supporting flashing(update)?

**Comment by felHR85** [comment]
@v2kb2l I guess it depends of whatever device you want to flash. What are you want to flash?

**Comment by v2kb2l** [comment]
I would like to update bin/out file to CC1350 Launch pad using USB serial.

**Comment by felHR85** [comment]
@v2kb2l It should be possible if it uses a serial connection for flashing but probably you have to implement the flashing protocol above UsbSerial.
