### ISSUE TITLE
setBreak implementations for CP2102

### ISSUE THREAD

**Issue by winy57** [felHR85/UsbSerial#260]
Hi, currently on class CP2102SerialDevice, the setBreak(boolean state) method is not implemented. 

`@Override
    public void setBreak(boolean state)
    {
        //TODO Auto-generated method stub
    }`

Are you planning to add it soon?

Thanks

**Comment by winy57** [comment]
Hi, I've created a pull request : https://github.com/felHR85/UsbSerial/pull/261 :)

**Comment by felHR85** [comment]
Added in 6.1.0
