### ISSUE TITLE
Support USB HID?

### ISSUE THREAD

**Issue by GanZhiXiong** [felHR85/UsbSerial#264]

**Comment by felHR85** [comment]
@GanZhiXiong What kind of USB hid?

**Comment by GanZhiXiong** [comment]
I don't know exactly, but you can Google it: Android usb hid

**Comment by felHR85** [comment]
@GanZhiXiong [Please refer to this issue](https://github.com/felHR85/UsbSerial/issues/175)

**Comment by GanZhiXiong** [comment]
@felHR85  OK,Thanks!
