### ISSUE TITLE
Ayuda para usar en MIT inventor de aplicaciones

### ISSUE THREAD

**Issue by horaciocastro7** [felHR85/UsbSerial#311]
Hay alguna forma de que nos puedan ayudar a hacer algo similar.

https://github.com/kinsamanka/usbfai

Somos muchos los que trabajamos con Arduino y no tenemos muchos conocimientos en programación. De antemano agradezco cualquier ayuda.

**Comment by felHR85** [comment]
@horaciocastro7 
Hola Horacio,
Probablemente una descripción más detallada sea mejor por si alguien se ofrece voluntario. Por otra parte ponerlo también en inglés ayudará a alcanzar más gente.

Saludos
