### ISSUE TITLE
Kitkat/ Port is Null or not open

### ISSUE THREAD

**Issue by rick747** [felHR85/UsbSerial#34]
Hi, I tried your library with a number of different devices.
The connected cable always stays the same (FTDI chipset).

I tried 2 devices with Android Lollipop, 1 with Marshmellow and they work very well.
On the other hand, when I try the same app on 2 devices that have kitkat installed and another one that still has Jellybean, the behavior is quite strange.

```
I can register the Receiver
It does find the device (usb device is not empty)
I then request permission
in Broadcast Receivers onReceive() method permission is granted
```

But as soon as it reaches the following line:
serialPort = UsbSerialDevice.createUsbSerialDevice(device, connection);
serialport on my Samsung Note 2 (Kitkat 4.4) cannot open or port is null (another Kitkat device).

What puzzles me is the following. From time to time when I detach and reattach the cable, the connection all of a sudden can be opened and logcat shows
I/FTDISerialDevice: Interface succesfully claimed
I/FTDISerialDevice: Control Transfer Response: 0
Unfortunately, I cannot realibly predict, if and when this happens.

Do you have an idea what the reason for this behavior might be. As a sidenote, I also found out that for Version < Lollipop the permission dialog does not always appear, as it should. If I understand correctly the call usbManager.requestPermission(device, pendingIntent); should trigger it

**Comment by felHR85** [comment]
Hi @rick747 
That's weird. Are you using the example provided with the library. My tests with 4.4 were all OK but I will check it out as soon as possible.
