### ISSUE TITLE
How to all data at once instead of getting it character by character

### ISSUE THREAD

**Issue by karan221291** [felHR85/UsbSerial#38]
I am using example provided with this library, my problem is that I am getting data character by character inside onReceivedData() method. I want to know how to get data in one string so that I can pass it to activity and set it in my view. 

I need to read data continuously is there any facility like this available in the libarary

**Comment by felHR85** [comment]
Hi @karan221291 
Some devices doesnt send the data continously (Maybe it is a problem of some Android tablets).
It is easy to solve using a buffer and appending the data there till you receive everything you want.

You could use the synchronous version (described in the README file) to set the max length you want to read but this wouldnt solve the hardware problematic.

**Comment by karan221291** [comment]
@felHR85 what condition do i need to check that tells me data received from my serial machine has ended? is there any way by which i can use library for below scenario

-open connection with serial device
-get data continuously from serial device until connection is closed.

**Comment by felHR85** [comment]
If you are using some kind of protocol you should know when end of data is reached.
If there is no end. Just append characters to a buffer and set the buffer to a TextView for example.

Both of them can be done easily.

**Comment by karan221291** [comment]
@felHR85 thanks for quick reply, can you provide any example for how to use buffer in this situation, I don't know how to use as we will  not be able to get input & output streams.

**Comment by Ayyan-coditas** [comment]
@karan221291  Did you find a solution for this? I am also stuck with this problem and it would be wise to post a solution for future readers.

**Comment by mahermeg17** [comment]
Hi,
I get this problem when reading from UART port with a PICO PI IMX6UL board.
But when using an other usb library, it can read the message in one piece. So I thing it's an issue with the UsbSerial library. Sorry I don't know how to fix it.
The lib that I use to confirm : https://github.com/mik3y/usb-serial-for-android

Bests,
