### ISSUE TITLE
The app crashes if I attach a usb device, then deny the permissions and detach the usb device

### ISSUE THREAD

**Issue by josejuansanchez** [felHR85/UsbSerial#52]
You can replicate the crash following the next steps:
1. Attach the usb device
2. Deny the permissions
3. Detach the usb device

**Comment by bmdalton** [comment]
Update: if you have the issue of the app crashing after you detach the USB device (when it was functionally working at whatever you need it to do), this does NOT fix that.

**Comment by felHR85** [comment]
Fix issue is still not merged. @bmdalton Did you try it on the pull request branch?

**Comment by bmdalton** [comment]
I have.  I have a copy of the code running in Android Studio, so I physically made the changes there.  In both the original and the updated version, I have the same crash, which I have discovered is the result of modification of one line of code.

In your sample app, you have
<img width="841" alt="screen shot 2016-06-28 at 4 02 45 pm" src="https://cloud.githubusercontent.com/assets/19672758/16430631/8d4f5586-3d4a-11e6-94f9-b0995501aeff.png">
while I have updated this to be
<img width="660" alt="screen shot 2016-06-28 at 4 03 10 pm" src="https://cloud.githubusercontent.com/assets/19672758/16430647/a2b4a534-3d4a-11e6-8d21-b8f808828b0e.png">

As you can see, I change  "mActivity.get().display.append(data);" to "mActivity.get().setData(dataS);" which subsequently causes the crash.  When I comment out that line, the app does not crash when I disconnect the USB device however it also doesn't function.

**Comment by josejuansanchez** [comment]
@bmdalton You are right, the proposed PR in #53 only solves the issue described in the title :)

**Comment by abhishekkumar1902** [comment]
any solutions for this crash issue?
