### ISSUE TITLE
Is there a jar file?

### ISSUE THREAD

**Issue by sidgharge** [felHR85/UsbSerial#54]
I read on a website how to communicate with arduino with android. 
link is here    http://www.allaboutcircuits.com/projects/communicate-with-your-arduino-through-android/
They are telling to copy a jar file, but i couldnt find it. Im new to android developing. Help me plz, thanks in advance

**Comment by felHR85** [comment]
Hello @sidgharge 
There is no more need for a jar file. Just follow this:
Add the jitpack repo to your your project's build.gradle at the end of repositories

/build.gradle
```groovy
allprojects {
	repositories {
		jcenter()
		maven { url "https://jitpack.io" }
	}
}
```

Then add the dependency to your module's build.gradle:

/app/build.gradle
```groovy
compile 'com.github.felHR85:UsbSerial:4.3'
```
