### ISSUE TITLE
CDC_SET_CONTROL_LINE_STATE always 0x0003

### ISSUE THREAD

**Issue by paolo68** [felHR85/UsbSerial#56]
Hi, 
I noticed that with CDC you always set 
CDC_SET_CONTROL_LINE_STATE = CDC_CONTROL_LINE_ON = 0x0003

This causes problems when connecting to my 3D Printer (Arduino Mega board with Marlin firmware): strange characters are sent to printer, I need to do an hard reset before getting it to work.
Problems disappear if I modify your code to set CDC_CONTROL_LINE_OFF = 0x0000.

I do not know much about flow control... but maybe in this case it is better to set CDC_CONTROL_LINE_OFF by default, or anyway when flow control is OFF. 
What do you think?

BTW, great lib!

**Comment by felHR85** [comment]
Hi @paolo68 
Sorry for the delayed response. I will check it out as soon as possible because some implementations of the CDC profile are tricky in some devices.
