### ISSUE TITLE
Example calls thread.run() instead of thread.start()

### ISSUE THREAD

**Issue by csobsidian** [felHR85/UsbSerial#60]
In UsbService.java of the example application the BroadcastReceiver calls the thread to start with run().

`new ConnectionThread().run();`

This will merely call the thread run() code on the _current_ thread. To correctly call this code in a separate thread this should be changed to call start().

`new ConnectionThread().start()`

**Comment by felHR85** [comment]
Thank you @csobsidian !
It has been changed.
