### ISSUE TITLE
UsbSerialDevice.isSupported() Enhancement

### ISSUE THREAD

**Issue by csobsidian** [felHR85/UsbSerial#61]
It would be nice to have a way to determine if a device is supported without having to instantiate and then abandon a driver to do so. An android device might be used to control a set of external devices on a  machine, for example, and allow the user to pick which functionalities are present on each specific device. Attempting instantation of a driver for each device found on the OS is not an efficient method for building a list to present to the user.

I propose the following as a static method on the UsbSerialDevice class:

```
public static boolean isSupported(UsbDevice device)
{
    int vid = device.getVendorId();
    int pid = device.getProductId();

    if(FTDISioIds.isDeviceSupported(vid, pid))
        return true;
    else if(CP210xIds.isDeviceSupported(vid, pid))
        return true;
    else if(PL2303Ids.isDeviceSupported(vid, pid))
        return true;
    else if(CH34xIds.isDeviceSupported(vid, pid))
        return true;
    else if(isCdcDevice(device))
        return true;
    else
        return false;
}
```

This method would need to be maintained with new drivers as added per the createUsbSerialDevice() method.

TAG: Enhancement

**Comment by felHR85** [comment]
Method added
