### ISSUE TITLE
Will it work for CP2101

### ISSUE THREAD

**Issue by anugrah8** [felHR85/UsbSerial#71]
Hey, Thanks for the code,
I want to use CP2101 to communicate with UART, do I need to do any other thing like modifying the kernel or I can use it directly.

**Comment by felHR85** [comment]
Hi! @anugrah8 
Try it directly :)

**Comment by anugrah8** [comment]
Thanks for reply, I tried and it worked.
Now I want to ask that if I want to store data every time when receiving in an array than in which function I should do it, while my program is busy in some other class or method, (like we can do in Embedded c by generating interrupt call routine). In simple words we can save the data any time it come to Rx pin, no matter what our program is busy in some other thing.
Thanks
