### ISSUE TITLE
Read with Length

### ISSUE THREAD

**Issue by tjstyle** [felHR85/UsbSerial#74]
Hi..

are this library can read specific length like on C programming:
byte[] readBuffer = serial.read(5); //to read only 5 bytes in C

Regards,
TJ.

**Comment by felHR85** [comment]
Hi @tjstyle 
I would do it this way for reading 3 bytes for example:

byte[] buffer = new byte[3];
syncRead(buffer, 0);

**Comment by tjstyle** [comment]
Hi @felHR85 
Thanks for your suggestion. 
there are any example for using sync operation for read & write?

Regards,
TJ.

**Comment by felHR85** [comment]
Hi @tjstyle 
This weekend I've added a little example based on the previous one using the synchronous calls.
https://github.com/felHR85/UsbSerial/tree/master/examplesync

Hope it helps.
