### ISSUE TITLE
How can I use it for ARM devices ?

### ISSUE THREAD

**Issue by goelankita** [felHR85/UsbSerial#85]
Hello,

I want to connect a device which my organization builds. These are ARM based devices. When I use this app, it says, "Not supported". How can I use it for my device ?

**Comment by felHR85** [comment]
Are you talking about UsbSerial per se or just Droidterm?
If it shows not supported it is because you are connecting a USB-to serial converter not supported (Maybe because its vid and pid are not still listed).
UsbSerial and Droidterm work perfectly on ARM based Android devices
