### ISSUE TITLE
How to communicate with more than one USB Serial devices

### ISSUE THREAD

**Issue by suyog44** [felHR85/UsbSerial#88]
I am trying to make android code work which can communicate with multiple USB serial devices and android tablet.

I am able to communicate with single USB device at a time. but, now when I try to connect and communicate with multiple USB serial device App is failing.

**Comment by jiuwu0905** [comment]
I am also look for the solution of can not communicate multiple USB serial devices.

**Comment by jamesjude123** [comment]
public void openDevice()
    {
        connection = usbManager.openDevice(printer);
        debug.append("printer:  "+printer +"\n");
        debug.append("connection:  "+connection+"\n");
        serialDevice = UsbSerialDevice.createUsbSerialDevice(printer, connection);
        debug.append("serialDevice:  "+serialDevice.toString()+"\n");
        if (serialDevice != null) {
            if (serialDevice.open()) {
                serialDevice.setBaudRate(9600);
                serialDevice.setStopBits(UsbSerialInterface.STOP_BITS_1);
                serialDevice.setParity(UsbSerialInterface.PARITY_NONE);
                serialDevice.setFlowControl(UsbSerialInterface.FLOW_CONTROL_OFF);
                serialDevice.setRTS(true);
             //   serialDevice.read(mCallback);
            } else {
                debug.append("Printer port not open \n");
            }
        } else {
            debug.append("Serial is null \n");
        }
    }

**Comment by felHR85** [comment]
[Added Multiple Serial port Api](https://github.com/felHR85/UsbSerial/wiki/7.-Multiple-Serial-ports)
