### ISSUE TITLE
USB/Serial device doesn't show up in UsbManager#getDeviceList()

### ISSUE THREAD

**Issue by BenLeggieroNCR** [felHR85/UsbSerial#9]
I need to use this (os a similar) library to interface with a device which is connected like this: [![](https://i.imgur.com/BJLKt3g.png)](https://i.imgur.com/BJLKt3g.png)

but it doesn't show up when I call `usbManager.getDeviceList()`. I do get multiple devices, but not the one I connected like above (I know the other devices' `vendorId`s, plus the list size doesn't change when I plug/unplug the device).

**Comment by felHR85** [comment]
If usbManager.getDeviceList() is getting no response it is an Android issue. I would you recommend you trying with my app DroidTerm and see if it works properly

**Comment by BenLeggieroNCR** [comment]
It is getting a response. The response has two devices in it, but those are known devices, and they are the only devices in that list, regardless of whether External Device is plugged in.

I will try to use DroidTerm and get back to you.

**Comment by BenLeggieroNCR** [comment]
It is getting a response. The response has two devices in it, but those are known devices, and they are the only devices in that list, regardless of whether External Device is plugged in.

I don't see how I can use DroidTerm, since this is not a device with the Google Play Store. Do you have an APK or the source code, so I can install it on our Android Device?

**Comment by felHR85** [comment]
Try to test with other phones or tablets too.

**Comment by BenLeggieroNCR** [comment]
We don't have phones or tablets with USB-A F ports, nor a USB-A F to USB Micro-B M cable.

**Comment by BenLeggieroNCR** [comment]
That appears to be incompatible with Android API 17. Do you have an email where we can continue this?

**Comment by felHR85** [comment]
felhr85 at gmail.com

**Comment by BenLeggieroNCR** [comment]
This turned out to be a cable issue. It was resolved by using a cable with a PL2303 chipset.
