### ISSUE TITLE
Seem to be having some issues with Baud Rate

### ISSUE THREAD

**Issue by skipe777** [felHR85/UsbSerial#91]
I have been attempting to use the UsbSerial library on Android (Nexus 7 with Marshmallow). I have an FTDI Usb to 232 cable connected up through a OTG cable. The other end is an ODROID C2 running Ubuntu Linux. I have tested the cable and the connection to the linux machine up to a Baud Rate of 230400. I have been trying to get the Android->Linux connection working at 115200, but haven't been able to get data over 9600. Once I turn it up to anything higher I no longer see it on the other end (or its just garbage).

I am operating in non-canonical / raw input on the other side so I am just reading single bytes. I guess I should also note that I am seeing echoing on the line on the Android side and I have tried both Async and the Sync calls.

Has anyone used the library at 115200 (or higher) with any success? I am using the example code provided in for the Sync calls at this point. Is anyone else seeing any echoing of their own sent data?

I can provide the Linux code if necessary, but its pretty straight forward C++ that I have been using for years on other projects.

UPDATE (2/14/17):

I was able to get everything up and running with a max baud rate of 230400. However, I have to use stty on the command line to set the baud rate. The termios attribute calls don't seem to do anything and leave the port at 9600 at all times. Anyone else have this behavior? I haven't had this happen on any system I have used this code on before.

**Comment by AdrianDC** [comment]
Same issue on my setup while I was trying to move away from Physicaloid.

I'm working on Android serial communication with an ARM mbed 1768,
and I can configure the baudrate dynamically on both sides.

The library doesn't apply the baudrate requests,
it is always stuck on 9600 although the CDC should be 115200 by default.

**Comment by jzaruba** [comment]
Same here. Using putty I can talk to my Arduino at whatever baud-rate. Using the library I am stuck at 9600.

**Comment by jzaruba** [comment]
Turns out the issue I was facing seems to be non-present when using genuine Arduino Uno, rather than a clone I was using before that. The question is whether the issue lies within the clone hardware or the class handling its chip: CH34xSerialDevice.java.

**Comment by jzaruba** [comment]
Tested with geniune Arduino/CDCSerialDevice and a clone NHduino/CH34xSerialDevice. Apparently USBSerial can only talk to hose only at whatever is the default baud rate in their respective Java classes: 9600 for the clone and 115200 for Arduino. (Admittedly, with the Arduino I only tested 115200 and 230400.)

**Comment by jzaruba** [comment]
I can attest that modifying default baud rate in CDCSerialDevice.java worked for me. Now my Android app talks to (genuine) Arduino working at baud rate of 230400. You need to modify different class when using a clone, most likely CH34xSerialDevice.java.
