### ISSUE TITLE
App crash when "createUsbSerialDevice"

### ISSUE THREAD

**Issue by williamtran1988** [felHR85/UsbSerial#97]
Hi All, 

I am having an issue when integrate with library. My application was crashed when "createUsbSerialDevice", 

i have 2 case as below:
- Plug USB to android device: ==> OK
   + App is open because i have device filter USB attached.
   + Can create a connection and open it.
- USB is already plugged.
   + Reboot android device.
   + Permission is granted.
   + openDevice success
   + createUsbSerialDevice ===> FAILED.

Could somebody help me on this?

**Comment by PawelSzymanski89** [comment]
i have simmilar issue...

**Comment by felHR85** [comment]
@PawelSzymanski89 Some info from Logcat would be great

**Comment by felHR85** [comment]
Hi @ToninoTarsi 
What Android version do you have? Also It would be great to take a look of the exception stacktrace

**Comment by ToninoTarsi** [comment]
Thanks Felipe
Android 6 ( LG G3 ) . For the stacktrace I will be happy to be able to provide you one but I have no idea on how to connect simultaneously the FDTI and the PC to my phone.  How do you do that ?
Regards

**Comment by felHR85** [comment]
Android 6 should work fine. What kind of UsbSerial device are you connecting? if createUsbSerialDevice is returning null that means the usb device "is not supported" because VID-PID are not recognized.
[For debugging through wifi try this](http://stuffandtech.blogspot.com/2012/03/android-quick-tip-adb-over-wifi.html)

**Comment by ToninoTarsi** [comment]
Thanks for the information about ADB ove WiFi  .. I will try. The device is an  FTDI ( device.getVendorId() return 1027 ) and your example sync works fine so it is supported and your library works fine.
The ADB over wifi will help to understand what I'm missing .. I hope.
Thanks

**Comment by felHR85** [comment]
@ToninoTarsi And the product id? Vendor id is standard FTDI but maybe that product id is not supported.

**Comment by ToninoTarsi** [comment]
PID = 24597 (dec )  0x6015

**Comment by felHR85** [comment]
@ToninoTarsi It should be supported

**Comment by ToninoTarsi** [comment]
Yes .. it works. It was my fault. Thanks for indicating me how to use ADB over Wifi .. I did not known that :-)
Regards
