### ISSUE TITLE
Custom vendor/product id?

### ISSUE THREAD

**Issue by i-schuetz** [felHR85/UsbSerial#98]
I'm working with some CP210x devices with a custom vendor/product id. Can I use this library? The ids seem to be fixed in `CP210xIds`. In e.g. https://github.com/mik3y/usb-serial-for-android it's possible to pass a custom table (just mentioning it because I genuinely wonder why it's possible there and not here)

**Comment by felHR85** [comment]
@i-schuetz  For any interested this will be solved in the next update.

**Comment by felHR85** [comment]
@i-schuetz Use 
```java
UsbSerialDevice serial = UsbSerialDevice.createUsbSerialDevice(UsbSerialDevice.FTDI, device, connection,0);
```
